# Generated by Django 2.2.16 on 2022-11-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20221104_1529'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='review',
            table=None,
        ),
    ]
