# Generated by Django 2.2.16 on 2022-11-09 10:09

import django.core.validators
from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_auto_20221109_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(reviews.validators.get_year)], verbose_name='Год произведения'),
        ),
    ]
